### ISSUE TITLE
/Staff for staff

### ISSUE THREAD

**Issue by TooMadd** [Barsik4/SMP-Issues#14]
So I'd like to add in a /Staff mode for staff so in case something happens with a player we can do /Staff which basically puts in a different mode like it'll give us a special game mode that gives us Things such as-  Fly Vanish BlockCheck worldedit (For grief purposes only) Inventory checker and other various things you can think of

**Comment by shadowolfyt** [comment]
Fly: You have XPFly
Vanish: That can be given to you
BlockCheck: Can be used with /co i
WE: That can be done (For grief purposes only) 
Inventory Checker: This can also be done

This means we will have to tighten who we make Moderator
